# Model hyperparameters
num_epochs              : 2
seed                    : 42

datasets  :
  Noise_division_factor : 7

model :
  name                    : "CNN-RNN"
  prediction_horizon      : 50
  prediction_input_size   : 200
  # Encoder

  # Decoder
  RNN_NumLayer            : 2

loss  :
  Eigen           : False
  alpha           : 1

# Optimization parameters
optimizer :
  name: SGD
  weight_decay    : 0.00
  momentum        : 0.00

# Scheduler parameters
scheduler:
  name: StepLR
  learning_rate   : 0.05
  step_size       : 5
  gamma           : 0.1 